baseURL = "https://tahumn.github.io/AWS-Internship-Portfolio/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "en"

# Hugo theme
theme = "hugo-theme-learn"

# Search functionality
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "workshop"

# GitHub repository link
editURL = ""
description = ""
author = "thienlh@thienlu.com"

showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false

# =========================
# English
# =========================
[Languages]

[Languages.en]
title = "Internship Report"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 30

# =========================
# Vietnamese
# =========================
[Languages.vi]
title = "Báo cáo thực tập"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 30

# =========================
# Markdown
# =========================
[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true